name: yoto
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  cloud_firestore: ^4.3.1
  firebase_storage: ^11.0.10
  image_picker: ^0.8.6+1
  provider: ^6.0.5
  mobx: ^2.1.3
  flutter_mobx: ^2.0.6+5
  universal_html: ^2.2.4
  geolocator: ^12.0.0
  intl: ^0.19.0
  flutter_chat_ui: ^1.6.15
  socket_io_client: ^2.0.3+1
  get_it: ^7.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  mobx_codegen: ^2.1.1

flutter:
  uses-material-design: true